# Generated by Django 3.2.9 on 2021-11-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
