# Generated by Django 3.2.9 on 2021-11-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_post_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
