# Generated by Django 3.2.9 on 2021-11-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='thumbnail',
            new_name='img',
        ),
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
