# Generated by Django 3.2.9 on 2021-11-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211129_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='img',
            new_name='thumbnail',
        ),
    ]
