# Generated by Django 3.2.9 on 2021-11-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='./images/profiles'),
        ),
    ]
